---
title: "visualization 2"
author: "Nhu Nguyen"
date: "2023-10-05"
output: github_document
---
loading necessary libraries 
```{r}
library(tidyverse)
library(patchwork)
```

## loading the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

weather_df
```

## remember this plot? 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5)
```
this plot is good for me to know what is going on in the graph, but if someone else were to look at this graph, they might not know what tmin or tmax is -- might be helpful to have a caption 

## labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
    title = "temperature plot", 
    x = "minimum daily temperature (x)",
    y = "maximum daily temperature (y)", 
    caption = "data from the rnoaa package: temperatures in 2017"
  )
```



