---
title: "exploratory analysis"
author: "Nhu Nguyen"
date: "2023-10-05"
output: github_document
---

```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

loading necessary libraries 
```{r}
library(tidyverse)
library(patchwork)
```

## loading the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())

weather_df
```

## `group_by`

```{r}
weather_df %>% 
  group_by(name)
```
## counting things

count month/name observations
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(n_obs = n())
```
we can use `count()` 

```{r}
weather_df %>% 
  count(month, name = "n_obs")
```

**NEVER** use base R's `table` function 
  - not helpful -- can't use this data for further analysis
```{r, eval = FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
```
other helpful counters

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```
- in summarize, we have given it two things to summarize -- created 2 variables, # of observations and # of days


